import React from "react";
import LeftProject from "./LeftProject";
import RightProject from "./RightProject";

const porj1_desc = `
***Tools***: Next.js, Tailwind, GraphQL, StepZen, Tremor 2.0, OpenAI

***Duration***: May 2023 - August 2023

I developed GPT-Weather, a Next.js web application, to revolutionize weather forecasting. By seamlessly integrating OpenMeteo API data into a GraphQL database using StepZen, the application ensures optimized data retrieval and accurate predictions.

With dynamic visualization using the Tremor 2.0 UI library, users can explore humidity, rain probability, and temperature trends interactively. 

Additionally, insightful weather summaries generated by OpenAI enhance user understanding. The tech stack includes Next.js, Tailwind, OpenMeteo API, GraphQL, StepZen, Tremor 2.0, and OpenAI.

`;

const proj2_desc = `
  ***Tools***: Python, NLTK, Scikit-learn, Matplotlib

***Duration***: May 2023 - August 2023 

I developed a YouTube Ad Recommender where I utilized NLTK for text processing and Scikit-learn for classification.

Achieved impressive 97% (Naive Bayes) and 98% (SVM) accuracies in multi-class video category classification.

Evaluated with precision-recall curves on a dataset of 3000 videos and 6300 advertisements, demonstrating my ability to deliver robust content recommendation solutions.


`;

const proj3_desc = `
***Tools***: HTML, CSS, JavaScript, PHP, MySQL


***Duration***: March 2022 - April 2022



Created a complete real estate website called Bongora Tehsildar. This website allows you to list properties, find matching agents, and easily search for properties.

Built a smart system to organize and store data efficiently using a MySQL database. To make everything secure,

Used PHP to manage communication between the website and the database.


`;
type Props = {};

function Projects({}: Props) {
  return (
    <div className="min-h-screen flex flex-col  items-center mt-10 ">
      <h3 className=" uppercase tracking-[20px] md:tracking-[25px] text-slate-500 text-xl md:text-3xl font-bold">
        Projects
      </h3>

      <div className="flex flex-col">
        <LeftProject
          img_url="proj1"
          title="GPT-Weather: Next.js Web App for Advanced Weather Forecasting"
          body={porj1_desc}
          link=""
          url="https://weather-gpt-seven.vercel.app"
          github="https://github.com/p-rohitt/weather-gpt"
        />
        <RightProject
          img_url="proj3"
          title="Youtube Ad Recommender"
          body={proj2_desc}
          link=""
        />
        <LeftProject
          img_url="proj4"
          title="Real Estate Management Portal"
          body={proj3_desc}
          link=""
          url=""
          github= "https://github.com/p-rohitt/real-estate-web"
        />
      </div>
    </div>
  );
}

export default Projects;
